### ISSUE TITLE
Comment the java classes meaningfully. 

### ISSUE THREAD

**Issue by ChathuminaVimukthi** [ChathuminaVimukthi/Object-Oriented-Programing#2]

**Comment by bravoo84** [comment]
I am completely a newbie to open source but when I looked into your project I can easily work with it..can u please explain me what to do!? @ChathuminaVimukthi

**Comment by ChathuminaVimukthi** [comment]
Choose a java file and comment the code meaningfully and yes I made these issues to help the new comers.. Glad to see one.
Good luck :)

**Comment by bravoo84** [comment]
Ok..so I have to comment functioning of just classes and methods in your java file?

**Comment by ChathuminaVimukthi** [comment]
yeah.. thats all

**Comment by bravoo84** [comment]
Commented WestMinisterCarParkManager.java file @ChathuminaVimukthi 

[Commit1.zip](https://github.com/ChathuminaVimukthi/Object-Oriented-Programing/files/1425393/Commit1.zip)

**Comment by ChathuminaVimukthi** [comment]
Great :)

Keep contributing to open source!
Cheers!

**Comment by bravoo84** [comment]
@ChathuminaVimukthi Can you explain what to do for hackoctober fest 2017?
I do not know how to create a pull request!

**Comment by bravoo84** [comment]
#4

**Comment by ChathuminaVimukthi** [comment]
If you don't know about hacktoberfest visit this link to get some info - https://hacktoberfest.digitalocean.com

and to make a pull request..otherwise these changes will not be merged into the original repo..if you don't know how to make a pull request the bellow link will provide you a brief intro on how to make a pull request.

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

Keep contributing :)
